config/routes.rb
Rails.application.routes.draw do
  resources :supporters
  get "/supporters/:id/done" => "supporters#done", as: :done_supporter

end

app/models/supporter.rb
class Supporter < ActiveRecord::Base
  validates :name, presence:   true
  validates :email, presence:   true

  after_initialize :set_default_values
  
  private

  def set_default_values
   self.photo ||= "Not Done"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/supporters_controller.rb
class SupportersController < ApplicationController

before_action(:find_supporter, {only: [:show, :edit, :update, :destroy, :done]})

    def new
      @s = Supporter.new
    end

    def create
      @s = Supporter.new(supporter_params)
      if @s.save
        redirect_to(supporter_path(@s), notice: "Supporter created!")
      else
        render :new
      end
    end

  def show
  end

  def edit
  end

  def update
    if @s.update(supporter_params)
      redirect_to supporter_path(@s), notice: "Request updated!"
    else
      render :edit
    end
  end

  def index
    @s = Supporter.all
  end

  def destroy
    @s.destroy
    flash[:notice] = "Request deleted successfully"
    redirect_to supporters_path
  end

  def done
    if @s.photo == "Not Done"
      @s.update_attributes(:photo => "Done")
    else
      @s.update_attributes(:photo => "Not Done")
    end
    @s = Supporter.all.order(:photo).reverse
    render :index
  end

  private

  def supporter_params
    params.require(:supporter).permit([:name, :email, :department, :message, :photo])
  end

  def find_supporter
    @s = Supporter.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/supporters_helper.rb
module SupportersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupporterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

<%= yield %>
</div>
</body>
</html>

app/views/supporters/_form.html.erb
<%= @s.errors.full_messages.join(", ") %>

<%= form_for @s do |f| %>
<div class="form-group">
    <%= f.label(:name) %>
    <%= f.text_field(:name, {class: "form-control"}) %>
    <p class="help-block">Enter the Supporter's Name</p>
</div>
<div class="form-group">
   <%= f.label(:email) %>
   <%= f.text_field :email, class: "form-control" %>
   <p class="help-block">Enter the Supporter's Email</p>
</div>
<div class="form-group">
    <%= f.label(:department, 'Sales', :value => 'sales', checked: true) %>
    <%= f.radio_button(:department, 'sales') %>
    <%= f.label(:department, 'Marketing', :value => 'marketing')%>
    <%= f.radio_button(:department, 'marketing')%>
    <%= f.label(:department, 'Technical', :value => 'technical')%>
    <%= f.radio_button(:department, 'technical')%>
</div>
<div class="form-group">
   <%= f.label(:message) %>
   <%= f.text_area :message, class: "form-control" %>
   <p class="help-block">Enter the Message</p>
</div>
<%= f.submit({class: "btn btn-primary"}) %>
<% end %>

app/views/supporters/edit.html.erb
<h1>Edit Support Request</h1>

<%= render "form" %>

app/views/supporters/index.html.erb
<h1>Support Requests</h1>
<table border=1;>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Message</th>
      <th>Action</th>
    </tr>
    <tbody>
      <tr>
        <% @s.each do |r| %>
        <td><%= r.name %></td>
        <td><%= mail_to r.email, r.email %></td>
        <td><%= r.department %></td>
        <td><%= r.message %></td>
        <td><%= link_to "Edit", edit_supporter_path(r), class: "btn btn-info btn-sm"%>
            <%= link_to("Delete", supporter_path(r), {method: :delete,
                                                  class: "btn btn-danger btn-sm",
                                                  data:   {confirm: "Are you sure?"}}) %>

            <%= link_to "#{r.photo}", done_supporter_path(r), class: "btn btn-info btn-sm"%></td>

      </tr>
      <% end %>
      </tbody>
</table>

app/views/supporters/new.html.erb
<h1>New Supporter</h1>
<%= render "form" %>

app/views/supporters/show.html.erb
<h1>Support Request</h1>
<table border=1;>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Message</th>
      <th>Action</th>
    </tr>
    <tbody>
      <tr>
        <td><%= @s.name %></td>
        <td><%= @s.email %></td>
        <td><%= @s.department %></td>
        <td><%= @s.message %></td>
        <td><%= link_to "Edit", edit_supporter_path(@s), class: "btn btn-info btn-sm"%>
            <%= link_to("Delete", supporter_path(@s), {method: :delete,
                                          class: "btn btn-danger btn-sm",
                                          data:   {confirm: "Are you sure?"}}) %></td>
      </tr>
      </tbody>
</table>